#pubspec.yaml
name: iamatpark
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  test: ^1.25.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/on1.png
    - assets/on2.png
    - assets/on3.png
    - assets/facebook.png
    - assets/google.png
    - assets/bg4.png
